//! Build script for `media-rs`.
//!
//! At build time this script obtains the prebuilt **static** FFmpeg libraries (and the codec/support libraries they
//! depend on) for the current target and links them statically into the crate.
//!
//! The raw FFI bindings are **not** generated here — they are pre-generated by the `xtask` crate across a per-OS CI
//! matrix and committed to `src/sys/bindings.rs`, so building this crate needs neither `bindgen` nor `libclang`.
//!
//! Binaries come from: https://github.com/vegidio/binaries-ffmpeg/releases
//!
//! The binaries are normally downloaded from the pinned release and cached under the build's `OUT_DIR`. To build
//! offline (or against a custom build of FFmpeg), set the `MEDIA_BINARIES_DIR` environment variable to a directory that
//! contains `include/` and `lib/` subdirectories laid out like the release archives.
//!
//! ## Linking
//!
//! The bundled set of dependency libraries differs per platform/architecture (e.g. nvcodec/qsv/opengl ship on
//! windows-x64 but not windows-arm64; vaapi is Linux-only). Rather than hardcode a per-target list, the script
//! *discovers* every static library in `lib/` and links them all, emitting the FFmpeg core libraries first in
//! dependency order and the rest afterward. The archive naming differs by toolchain: GNU/macOS builds ship
//! `lib<name>.a`, while the Windows builds are now **MSVC** and ship `<name>.lib` (the core libs without a `lib`
//! prefix, e.g. `avcodec.lib`). On GNU linkers (Linux) the whole set is wrapped in `--start-group`/`--end-group` to
//! resolve the circular references between FFmpeg and its dependencies; the macOS (`ld64`) and MSVC (`link.exe`)
//! linkers are multi-pass and need no grouping.

use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// Version of the `binaries-ffmpeg` release to download. The single source of truth is the repo-root
/// `ffmpeg-version.txt`, read here (and by `xtask`) via `include_str!` so the pinned version only has to be bumped in
/// one place. `.trim()` tolerates a trailing newline.
fn ffmpeg_version() -> &'static str {
    include_str!("ffmpeg-version.txt").trim()
}

/// The eight FFmpeg core libraries, listed dependents-before-dependencies so that a single-pass linker resolves them.
/// Any other `.a` found in `lib/` (third-party codecs and support libraries) is linked after these.
const FFMPEG_CORE_LIBS: &[&str] = &[
    "avdevice",
    "avfilter",
    "avformat",
    "avcodec",
    "postproc",
    "swscale",
    "swresample",
    "avutil",
];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=ffmpeg-version.txt");
    println!("cargo:rerun-if-env-changed=MEDIA_BINARIES_DIR");

    let binaries_dir = locate_binaries();
    let lib_dir = binaries_dir.join("lib");

    emit_link_directives(&lib_dir);
}

/// Returns the directory containing the `include/` and `lib/` subdirectories, either from the `MEDIA_BINARIES_DIR`
/// override or by downloading + extracting the pinned release.
fn locate_binaries() -> PathBuf {
    if let Ok(dir) = env::var("MEDIA_BINARIES_DIR") {
        let dir = PathBuf::from(dir);
        assert!(
            dir.join("include").is_dir() && dir.join("lib").is_dir(),
            "MEDIA_BINARIES_DIR ({}) must contain `include/` and `lib/` subdirectories",
            dir.display()
        );
        return dir;
    }

    download_and_extract()
}

/// Downloads the static archive for the current target into `OUT_DIR` and extracts it.
/// Extraction is skipped if a previous build already populated the cache directory.
fn download_and_extract() -> PathBuf {
    let version = ffmpeg_version();
    let archive = archive_name();
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let cache_dir = out_dir.join(format!("binaries-ffmpeg-{version}"));

    // Idempotent: a fully extracted cache from a previous build is reused as-is.
    if cache_dir.join("lib").is_dir() && cache_dir.join("include").is_dir() {
        return cache_dir;
    }

    let url = format!(
        "https://github.com/vegidio/binaries-ffmpeg/releases/download/{version}/{archive}"
    );
    eprintln!("media-rs: downloading {url}");

    let bytes = download(&url);
    extract_zip(&bytes, &cache_dir);
    cache_dir
}

/// Maps the Cargo target triple components to the release archive file name,
/// e.g. `static_osx_arm64.zip`.
fn archive_name() -> String {
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap();
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap();

    let os = match target_os.as_str() {
        "linux" => "linux",
        "macos" => "osx",
        "windows" => "windows",
        other => panic!("media-rs: unsupported target OS `{other}`"),
    };

    let arch = match target_arch.as_str() {
        "x86_64" => "x64",
        "aarch64" => "arm64",
        other => panic!("media-rs: unsupported target architecture `{other}`"),
    };

    format!("static_{os}_{arch}.zip")
}

/// Downloads the given URL into memory, following redirects.
fn download(url: &str) -> Vec<u8> {
    let mut reader = ureq::get(url)
        .call()
        .unwrap_or_else(|e| panic!("media-rs: failed to download {url}: {e}"))
        .into_body()
        .into_reader();

    let mut bytes = Vec::new();
    io::copy(&mut reader, &mut bytes)
        .unwrap_or_else(|e| panic!("media-rs: failed to read response body from {url}: {e}"));
    bytes
}

/// Extracts a zip archive (held entirely in memory) into `dest`.
fn extract_zip(bytes: &[u8], dest: &Path) {
    let reader = io::Cursor::new(bytes);
    let mut zip = zip::ZipArchive::new(reader).expect("media-rs: invalid zip archive");

    for i in 0..zip.len() {
        let mut entry = zip.by_index(i).expect("media-rs: corrupt zip entry");
        let Some(rel_path) = entry.enclosed_name() else {
            continue; // skip unsafe / absolute paths
        };
        let out_path = dest.join(rel_path);

        if entry.is_dir() {
            fs::create_dir_all(&out_path).unwrap();
            continue;
        }

        if let Some(parent) = out_path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        let mut out_file = fs::File::create(&out_path)
            .unwrap_or_else(|e| panic!("media-rs: cannot create {}: {e}", out_path.display()));
        io::copy(&mut entry, &mut out_file).expect("media-rs: failed to extract file");
    }
}

/// Tells Cargo/rustc where the static libraries live and which ones to link, including
/// the C++ runtime and system libraries the codecs depend on.
fn emit_link_directives(lib_dir: &Path) {
    println!("cargo:rustc-link-search=native={}", lib_dir.display());

    let libs = discover_link_order(lib_dir);
    assert!(
        !libs.is_empty(),
        "media-rs: no static libraries (`lib*.a` / `*.lib`) found in {}",
        lib_dir.display()
    );

    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap();
    let target_env = env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();

    // GNU linkers (Linux) resolve symbols in a single pass, so the circular references between FFmpeg and its
    // dependencies require a link group. The macOS (`ld64`) and Windows MSVC (`link.exe`) linkers are multi-pass and
    // need no grouping. (The legacy `*-pc-windows-gnu` toolchain would also need a group, but the Windows archives are
    // now MSVC `.lib` files and only link under `*-pc-windows-msvc`.)
    let use_link_group = target_os == "linux" || (target_os == "windows" && target_env == "gnu");

    if use_link_group {
        println!("cargo:rustc-link-arg=-Wl,--start-group");
        for lib in &libs {
            println!("cargo:rustc-link-arg=-l{lib}");
        }
        println!("cargo:rustc-link-arg=-Wl,--end-group");
    } else {
        for lib in &libs {
            println!("cargo:rustc-link-lib=static={lib}");
        }
    }

    emit_system_libs(&target_os);
}

/// Discovers every static library in `lib_dir` and returns the link names ordered FFmpeg-core-first, dependencies
/// after.
///
/// The archive naming depends on the toolchain:
/// - **GNU/macOS** (`lib<name>.a`): strip the `lib` prefix and `.a` suffix → `<name>`.
/// - **MSVC** (`<name>.lib`): strip only the `.lib` extension (case-insensitively — the
///   archive contains `GlU32.Lib`/`OpenGL32.Lib`) and keep the stem verbatim, including any
///   `lib` prefix. MSVC `static=<name>` resolves `<name>.lib`, so the FFmpeg core libs link
///   as `avcodec`/`avformat`/… and prefixed deps as `libx264`/`libssl`/…; Windows's
///   case-insensitive filesystem matches `GlU32` → `GlU32.Lib`.
fn discover_link_order(lib_dir: &Path) -> Vec<String> {
    let msvc = env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("msvc");

    let mut found: Vec<String> = fs::read_dir(lib_dir)
        .unwrap_or_else(|e| panic!("media-rs: cannot read {}: {e}", lib_dir.display()))
        .filter_map(|entry| {
            let path = entry.ok()?.path();
            let name = path.file_name()?.to_str()?;
            let stem = if msvc {
                // `<name>.lib` / `<name>.Lib` — keep the stem as-is (no `lib`-prefix strip).
                let ext = path.extension()?.to_str()?;
                ext.eq_ignore_ascii_case("lib").then(|| &name[..name.len() - ext.len() - 1])?
            } else {
                name.strip_prefix("lib")?.strip_suffix(".a")?
            };
            (!stem.is_empty()).then(|| stem.to_string())
        })
        .collect();

    let mut ordered = Vec::with_capacity(found.len());

    // FFmpeg core libraries first, in dependency order.
    for core in FFMPEG_CORE_LIBS {
        if let Some(pos) = found.iter().position(|l| l == core) {
            ordered.push(found.swap_remove(pos));
        }
    }

    // Remaining third-party dependencies, in a stable (sorted) order.
    found.sort();
    ordered.extend(found);
    ordered
}

/// Emits the system libraries / frameworks that the FFmpeg static libs reference but that
/// are provided by the OS rather than bundled in the archive.
fn emit_system_libs(target_os: &str) {
    match target_os {
        "macos" => {
            println!("cargo:rustc-link-lib=dylib=c++");
            println!("cargo:rustc-link-lib=dylib=z");
            println!("cargo:rustc-link-lib=dylib=iconv");
            for framework in [
                "CoreFoundation",
                "CoreServices",
                "CoreMedia",
                "CoreVideo",
                "CoreAudio",
                "AudioToolbox",
                "VideoToolbox",
                "AVFoundation",
                "Foundation",
                "Metal",
                "Security",
                // libavfilter's text/drawing filters reference CoreText (and its
                // CoreGraphics dependency); the coreimage/opengl filters and avdevice pull
                // in CoreImage, OpenGL and AppKit.
                "CoreText",
                "CoreGraphics",
                "CoreImage",
                "OpenGL",
                "AppKit",
                "OpenCL",
                "QuartzCore",
                "IOSurface",
            ] {
                println!("cargo:rustc-link-lib=framework={framework}");
            }
        }
        "linux" => {
            println!("cargo:rustc-link-lib=dylib=stdc++");
            println!("cargo:rustc-link-lib=dylib=m");
            println!("cargo:rustc-link-lib=dylib=pthread");
            println!("cargo:rustc-link-lib=dylib=dl");
            println!("cargo:rustc-link-lib=dylib=z");
            // The Linux build is `--enable-vaapi`, so `libavutil`/`libavcodec` reference VA-API symbols. As of binaries
            // 26.6.0 these are **bundled** — the archive ships `libva.a`/`libva-drm.a`/`libdrm.a`, which
            // `discover_link_order()` picks up and links inside the `--start-group` above, so there is no host libva
            // dependency. VA-API (and NVENC/CUDA/QSV) still `dlopen` the GPU vendor driver at runtime (covered by
            // `-ldl`); no VDPAU symbols are referenced.

            // aarch64-only linker fixes for GNU `bfd` (the default linker there; x86_64 uses `rust-lld`, which needs
            // neither and even *rejects* the flag below — hence the gate).
            //
            // 1. `bfd` honours rustc's `--as-needed` positionally: a lib is kept only if it resolves an
            //    *already-undefined* symbol when it appears. The system libs sit *before* the FFmpeg `--start-group`,
            //    so by the time the group references libm or libgcc's aarch64 outline atomics those libs are already
            //    discarded -> "undefined reference". Re-listing them as link-args (rustc appends these *after* the
            //    group) makes the symbols undefined again, so `--as-needed` keeps them. `gcc` (static `libgcc.a`, for
            //    the outline atomics) resolves via the `cc` driver's search path.
            // 2. `__stack_chk_guard` is exported by the dynamic loader, a transitive `DT_NEEDED` of libc that bfd won't
            //    follow by default -> "DSO missing from command line". `--copy-dt-needed-entries` makes it follow
            //    libc's `NEEDED`; it must precede the trailing `-lc` to take effect.
            if env::var("CARGO_CFG_TARGET_ARCH").as_deref() == Ok("aarch64") {
                println!("cargo:rustc-link-arg=-Wl,--copy-dt-needed-entries");
                for lib in [
                    "stdc++", "m", "z", "pthread", "dl", "gcc", "gcc_s", "util", "rt", "c",
                ] {
                    println!("cargo:rustc-link-arg=-l{lib}");
                }
            }
        }
        "windows" => {
            // The release archives are now **MSVC** `.lib` files, built with vcpkg's `*-static-md` triplet (static
            // libraries, *dynamic* UCRT), so they link under the stock `*-pc-windows-msvc` Rust target. The MSVC target
            // links the UCRT / vcruntime automatically and the bundled C++ libs (abseil, x265, openh264, harfbuzz) are
            // MSVC-built against that same dynamic CRT — so there is no `c++`/`stdc++` to emit here (and no
            // `+crt-static`: it would clash with the `-static-md` libs).
            //
            // FFmpeg and its bundled dependencies reference a range of Win32 import libraries that the OS provides.
            // Over-listing is harmless — an unused `/DEFAULTLIB` adds nothing to the binary — so the set is generous
            // and grouped by the consumer that needs it.
            for lib in [
                // crypto: bcrypt (rng), openssl (libcrypto/libssl) cert + schannel
                "bcrypt", "crypt32", "secur32",
                // sockets / networking: ws2_32 (+ srt/zmq pull in iphlpapi)
                "ws2_32", "iphlpapi",
                // COM / general Win32
                "ole32", "oleaut32", "uuid", "user32", "gdi32", "advapi32", "shell32",
                "shlwapi", "psapi",
                // avdevice capture: DirectShow + Media Foundation + Video-for-Windows
                "strmiids", "mfplat", "mfuuid", "mf", "mfreadwrite", "vfw32", "ksuser",
                "wmcodecdspuuid",
                // hardware accel (d3d / dxva)
                "d3d9", "d3d11", "dxgi", "dxva2", "dxguid",
                // SDL2 (avdevice sdl output)
                "winmm", "setupapi", "version", "imm32", "cfgmgr32",
                // abseil symbolize
                "dbghelp",
            ] {
                println!("cargo:rustc-link-lib=dylib={lib}");
            }
        }
        _ => {}
    }
}
